//Создать переменную "item_1"
//    let name = "item_1"
//   console.log(name)

// Присвоить переменной "item_1" цифру 5
//  let item_1 = "5"
//  console.log(item_1)

//  Создать переменную "item_2"
//  let name2 = "item_2"
//  console.log(name2)

// Присвоить переменной "item_2"цифру 3
//  let item2 = "3"
//  console.log(item_2)

// Создать переменную "item_3"
//  let name3 = "item_3"
//  console.log(name3)

// Присвоить переменной "item_3"сложение item_1 и item_2
//  let item_1 = 5
//  let item_2 = 3

//  let item_3 = item_1 + item_2
//  console.log(item_3)

// Создать переменную "item_4"
//  let name4 = "item_4"
//  console.log(name4)

// Присвоить переменной "item_4"cтроку "Yolochka"
//  let item_4 = "Yolochka"
//  console.log(item_4)

// Вывести в консоль сложение "item_3"и "item_4"
//  let item_3 = 8
//  let item_4 = "Yolochka"

//  let addition = item_3 + item_4
//  console.log(addition)

// Вывести в консоль умножение "item_3"и "item_4"
//  let multiplication = item_3 * item_4
//  console.log(multiplication)

// Создать переменную "item_5"
// let name5 = "item_5"
// console.log(name5)

// Присвоить переменной "item_5"значение "item_3"
// let item_5 = "NaN"
// console.log(item_5)

// Создать переменную "item_6"
// let name6 = "item_6"
// console.log(name6)

// Создать переменную "item_6type"
// let name7 = "item_6type"
// console.log(name7)
// Создать переменную“ age_1” и присвоить ей значение 10
// Создать переменную“ age_2” и присвоить ей значение 18
// Создать переменную“ age_3” и присвоить ей значение 60
// Создать
// if в котором будите проверять значение переменной age_1
// Если age_1 < age_2, вывести в консоль“ You don’ t have access cause your age is” + age_1 + “It’ s less then”
// Если age_1 >= age_2 и age_1 < age_3, вывести в консоль“ Welcome!”
// Если age_1 > age_3, вывести в консоль“ Keep calm and look Culture channel”.
// Иначе выводите“ Technical work”.


// let age_1 = 10
// let age_2 = 18
// let age_3 = 60

// function checkAge(age) {
// if (age < age_2) {
// return "you don't have access cause your age is" + age + "it's less then";
// } else if (age >= age_2 && age < age_3) {
// return "Welcome, your age is" + age;
// } else if (age > age_3) {
// return "keep calm and look culture channel, u are" + age;
// } else {
// return "Technical work";
// }
// }

// console.log(checkAge(17));
// console.log(checkAge(18));
// console.log(checkAge(61));